version: '2'
services:
  web:
    image: "xwiki:lts-mariadb-tomcat"
    container_name: xwiki-mariadb-tomcat-web
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=xwiki-mariadb-db
    volumes:
      - ./xwiki-data:/usr/local/xwiki
    networks:
      - xwiki-nw
  db:
    image: "mariadb:10.5"
    container_name: xwiki-mariadb-db
    volumes:
      - ./xwiki.cnf:/etc/mysql/conf.d/xwiki.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xwiki
      - MYSQL_USER=xwiki
      - MYSQL_PASSWORD=xwiki
      - MYSQL_DATABASE=xwiki
    networks:
      - xwiki-nw

networks:
  xwiki-nw:
